export default `CREATE TABLE IF NOT EXISTS \`Annotation\` (
  \`annotationId\` INTEGER NOT NULL,
  \`messageId\` INTEGER NOT NULL,
  \`text\` TEXT NOT NULL,
  \`embedding\` TEXT NOT NULL,
  \`dateCreated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`annotationId\`)
);
CREATE INDEX IF NOT EXISTS \`MESSAGEIDINDEX\` ON \`Annotation\` (\`messageId\` ASC);

CREATE TABLE IF NOT EXISTS \`Completion\` (
  \`completionId\` INTEGER PRIMARY KEY AUTOINCREMENT,
  \`type\` TEXT NOT NULL,
  \`model\` TEXT NOT NULL,
  \`completionOptions\` TEXT NOT NULL,
  \`inputs\` TEXT NOT NULL,
  \`output\` TEXT NOT NULL,
  \`dateCreated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS \`Message\` (
  \`messageId\` INTEGER PRIMARY KEY AUTOINCREMENT,
  \`windowId\` INTEGER NOT NULL DEFAULT 0,
  \`role\` TEXT NOT NULL,
  \`text\` TEXT NOT NULL,
  \`completed\` INTEGER NOT NULL DEFAULT 0,
  \`dateUpdated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`dateCreated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS \`ShortTermMemory\` (
  \`shortTermMemoryId\` INTEGER PRIMARY KEY AUTOINCREMENT,
  \`model\` TEXT NOT NULL,
  \`inputs\` TEXT NOT NULL,
  \`summary\` TEXT NOT NULL,
  \`dateCreated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS \`Version\` (
  \`version\` VARCHAR(10) NOT NULL,
  \`stage\` VARCHAR(30) NOT NULL,
  \`isMigrated\` BOOLEAN NOT NULL DEFAULT FALSE,
  \`migrationScript\` MEDIUMTEXT NULL,
  \`dateUpdated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`dateCreated\` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);`